### PR TITLE
Added teleport hacks to the BMR AI to solve the NecroHazard mechanic

### PR DESCRIPTION
**Pull request by BrakusTapus**

### CODE REVIEW

**Comment by zbee** [comment]
Is this not a very blatant and obvious hack that would be quite the risk to bringing much, much more attention and ire to plugins?
(ignore me if this isn't just the blinking to a new location that it sounds and looks like)

**Comment by CarnifexOptimus** [comment]
it is a hack, but completly optional to enable. who cares if people want to take the risk and its not like this would be the first plugin to offer teleport or noclipping.

**Comment by zbee** [comment]
Sure, I was just commenting on one with a larger community having an option to do it automatically in content with others; seems to me like the biggest risk to the user and to the plugin community that I've seen.

**Comment by BrakusTapus** [comment]
> Sure, I was just commenting on one with a larger community having an option to do it automatically in content with others; seems to me like the biggest risk to the user and to the plugin community that I've seen.

The user has to literally go out of their way to enable this feature, the only reason the option to always use tp hack with other players is for players that multibox multiple clients.
you're being afraid of the word "hack" nothing more.
Half the plugins you already use could easily be picked up if SE put in the effort.

The sentiment here is simple, if you don't want to use it, then you have to literally do nothing.

**Comment by CarnifexOptimus** [comment]
The teleport hack for this mechanic can only be enabled in addition to AI and you aren't supposed to use AI with other strangers around anyway. So people who activate both are twice as careless about their account I guess...

**Comment by zbee** [comment]
> So people who activate both are twice as careless about their account I guess...
This sentiment is certainly accurate ha

> Half the plugins you already use could easily be picked up if SE put in the effort.
This however is not the focus of my concern, as I mentioned; all or most plugins could be easily merc'd by SE if they cared, yes. My concern here is how very blatant it would be to other players: inviting or forcing a response from SE, whether about the user (of course) or possibly even about plugins if a large amount of this plugin's community were to for some reason take this risk.

As you both mentioned, users shouldn't do that, which is certainly true; however it is still an option just right there presented, and is the most automatic and "exposed" way that I at least have ever seen that implements something so obviously cheating.
I agree this is totally a risk on the user, I am just saying that I think this is the biggest risk ever given to a user, and that I think it should have more consideration around it.

I would very much like to see a big warning on the "Teleport hack (Always)" option, or even for that to be removed.

But, it seems to me neither of you agree, fair enough, so I'll leave my comments at that.

**Comment by BrakusTapus** [comment]
> But, it seems to me neither of you agree, fair enough, so I'll leave my comments at that.

True, agree to disagree

**Pull request merged**
